version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: >-
    echo %APPVEYOR_BUILD_FOLDER%

    cd %APPVEYOR_BUILD_FOLDER%\CinegyType.RSS.Controller

    nuget restore
build:
  project: '\CinegyType.RSS.Controller\CinegyType.RSS.Controller.sln'
  verbosity: minimal
after_build:
- cmd: >-
    7z a Type.RSS.Controller-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\CinegyType.RSS.Controller\CinegyType.RSS.Controller\bin\Release\CinegyType.RSS.Controller.exe

    appveyor PushArtifact Type.RSS.Controller-%APPVEYOR_BUILD_VERSION%.zip

    7z a Type.RSS.Controller-%APPVEYOR_BUILD_VERSION%-PDB.zip %APPVEYOR_BUILD_FOLDER%\CinegyType.RSS.Controller\CinegyType.RSS.Controller\bin\Release\*.*

    appveyor PushArtifact Type.RSS.Controller-%APPVEYOR_BUILD_VERSION%-PDB.zip